from __future__ import annotations

import argparse
import os
import sqlite3
from pathlib import Path
from urllib.parse import urlparse

import psycopg2
from psycopg2.extras import execute_values


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SQLITE_PATH = ROOT / "attendance.db"


TABLE_ORDER = [
    "departments",
    "room_types",
    "attendance_status_types",
    "campuses",
    "buildings",
    "rooms",
    "school_terms",
    "instructors",
    "courses",
    "students",
    "admins",
    "it_admins",
    "super_admins",
    "users",
    "classes",
    "enrollments",
    "attendance_logs",
    "permissions",
    "role_permissions",
    "system_settings",
    "audit_logs",
    "support_tickets",
    "ticket_replies",
    "student_face_embeddings",
]


IDENTITY_COLUMNS = {
    "admins": "admin_id",
    "attendance_logs": "log_id",
    "attendance_status_types": "status_id",
    "audit_logs": "log_id",
    "buildings": "building_id",
    "campuses": "campus_id",
    "classes": "class_id",
    "courses": "course_id",
    "departments": "dept_id",
    "enrollments": "enrollment_id",
    "instructors": "instructor_id",
    "it_admins": "it_admin_id",
    "permissions": "permission_id",
    "rooms": "room_id",
    "room_types": "room_type_id",
    "school_terms": "term_id",
    "students": "student_id",
    "student_face_embeddings": "embedding_id",
    "super_admins": "super_admin_id",
    "support_tickets": "ticket_id",
    "ticket_replies": "reply_id",
    "users": "user_id",
}


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS departments (
    dept_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code VARCHAR(20) UNIQUE,
    dept_name TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room_types (
    room_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS attendance_status_types (
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code VARCHAR(20) UNIQUE NOT NULL,
    status_name VARCHAR(50) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS campuses (
    campus_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_name TEXT UNIQUE NOT NULL,
    location TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS buildings (
    building_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name TEXT NOT NULL,
    campus_id INTEGER NOT NULL REFERENCES campuses(campus_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(building_name, campus_id)
);

CREATE TABLE IF NOT EXISTS rooms (
    room_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(20),
    floor_level INTEGER,
    campus_id INTEGER NOT NULL REFERENCES campuses(campus_id),
    building_id INTEGER REFERENCES buildings(building_id),
    room_type_id INTEGER REFERENCES room_types(room_type_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS school_terms (
    term_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year VARCHAR(20),
    term INTEGER,
    start_date DATE,
    end_date DATE
);

CREATE TABLE IF NOT EXISTS instructors (
    instructor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_number VARCHAR(20) UNIQUE,
    last_name TEXT,
    first_name TEXT,
    email TEXT UNIQUE,
    dept_id INTEGER REFERENCES departments(dept_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses (
    course_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(20) UNIQUE,
    course_name VARCHAR(100),
    units INTEGER,
    dept_id INTEGER REFERENCES departments(dept_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_number VARCHAR(20) UNIQUE,
    last_name TEXT,
    first_name TEXT,
    email TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    face_data_path TEXT,
    user_type TEXT DEFAULT 'regular',
    password TEXT
);

CREATE TABLE IF NOT EXISTS admins (
    admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number TEXT UNIQUE,
    last_name TEXT,
    first_name TEXT,
    email TEXT,
    dept_id INTEGER REFERENCES departments(dept_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS it_admins (
    it_admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(20) UNIQUE,
    last_name TEXT,
    first_name TEXT,
    email TEXT UNIQUE,
    dept_id INTEGER REFERENCES departments(dept_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS super_admins (
    super_admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(20) UNIQUE,
    last_name TEXT,
    first_name TEXT,
    email TEXT UNIQUE,
    dept_id INTEGER REFERENCES departments(dept_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('instructor', 'it_admin', 'super_admin')),
    reference_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS classes (
    class_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER REFERENCES courses(course_id),
    room_id INTEGER REFERENCES rooms(room_id),
    instructor_id INTEGER REFERENCES instructors(instructor_id),
    section VARCHAR(10),
    day_of_week VARCHAR(10),
    start_time TIME,
    end_time TIME,
    term_id INTEGER REFERENCES school_terms(term_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS enrollments (
    enrollment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER REFERENCES students(student_id),
    class_id INTEGER REFERENCES classes(class_id),
    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance_logs (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER REFERENCES students(student_id),
    class_id INTEGER REFERENCES classes(class_id),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status_id INTEGER REFERENCES attendance_status_types(status_id),
    notes TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name TEXT UNIQUE NOT NULL,
    description TEXT,
    category TEXT
);

CREATE TABLE IF NOT EXISTS role_permissions (
    user_type TEXT NOT NULL,
    permission_id INTEGER REFERENCES permissions(permission_id),
    PRIMARY KEY (user_type, permission_id)
);

CREATE TABLE IF NOT EXISTS system_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT,
    setting_type TEXT,
    updated_by INTEGER REFERENCES users(user_id),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    category TEXT DEFAULT 'config',
    options TEXT,
    min_value REAL,
    max_value REAL,
    step_value REAL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS audit_logs (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(user_id),
    action TEXT NOT NULL,
    resource_type TEXT,
    resource_id INTEGER,
    details TEXT,
    ip_address TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS support_tickets (
    ticket_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT DEFAULT 'other',
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
    assigned_to INTEGER REFERENCES users(user_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ticket_replies (
    reply_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES support_tickets(ticket_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    message TEXT NOT NULL,
    is_internal BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student_face_embeddings (
    embedding_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
    model_name TEXT NOT NULL,
    embedding_json TEXT NOT NULL,
    source_image_path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id, model_name)
);

CREATE INDEX IF NOT EXISTS idx_support_tickets_user_id ON support_tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_priority ON support_tickets(priority);
CREATE INDEX IF NOT EXISTS idx_support_tickets_assigned_to ON support_tickets(assigned_to);
CREATE INDEX IF NOT EXISTS idx_support_tickets_created_at ON support_tickets(created_at);
CREATE INDEX IF NOT EXISTS idx_ticket_replies_ticket_id ON ticket_replies(ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_replies_created_at ON ticket_replies(created_at);
"""


DROP_SQL = """
DROP TABLE IF EXISTS
    ticket_replies,
    support_tickets,
    audit_logs,
    system_settings,
    role_permissions,
    permissions,
    student_face_embeddings,
    attendance_logs,
    enrollments,
    classes,
    users,
    super_admins,
    it_admins,
    admins,
    students,
    courses,
    instructors,
    school_terms,
    rooms,
    buildings,
    campuses,
    attendance_status_types,
    room_types,
    departments
CASCADE;
"""


def postgres_url_from_env() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise SystemExit("DATABASE_URL is required, for example postgresql://fras_user:password@localhost:5432/frasdb")
    if url.lower().startswith("sqlite"):
        raise SystemExit("DATABASE_URL must point to PostgreSQL for this migration")
    return url


def validate_postgres_url(url: str) -> None:
    parsed = urlparse(url)
    if parsed.scheme not in {"postgresql", "postgres"}:
        raise SystemExit("Postgres URL must start with postgresql:// or postgres://")
    if not parsed.hostname:
        raise SystemExit("Postgres URL is missing a hostname")


def sqlite_rows(sqlite_conn: sqlite3.Connection, table: str) -> tuple[list[str], list[tuple]]:
    cursor = sqlite_conn.execute(f"SELECT * FROM {table}")
    columns = [description[0] for description in cursor.description]
    rows = cursor.fetchall()
    return columns, rows


def normalize_row(table: str, columns: list[str], row: tuple) -> tuple:
    boolean_columns = {
        ("attendance_status_types", "is_active"),
        ("ticket_replies", "is_internal"),
        ("users", "is_active"),
    }
    values = []
    for column, value in zip(columns, row):
        if (table, column) in boolean_columns and value is not None:
            values.append(bool(value))
        else:
            values.append(value)
    return tuple(values)


def insert_table(pg_cursor, table: str, columns: list[str], rows: list[tuple]) -> None:
    if not rows:
        return

    quoted_columns = ", ".join(f'"{column}"' for column in columns)
    values = [normalize_row(table, columns, row) for row in rows]
    execute_values(
        pg_cursor,
        f'INSERT INTO "{table}" ({quoted_columns}) VALUES %s',
        values,
        page_size=500,
    )


def reset_identity_sequence(pg_cursor, table: str, id_column: str) -> None:
    pg_cursor.execute(
        """
        SELECT setval(
            pg_get_serial_sequence(%s, %s),
            COALESCE((SELECT MAX(%s) FROM %s), 1),
            COALESCE((SELECT MAX(%s) FROM %s), 0) > 0
        )
        """
        % (
            "%s",
            "%s",
            id_column,
            table,
            id_column,
            table,
        ),
        (table, id_column),
    )


def migrate(sqlite_path: Path, postgres_url: str, reset: bool) -> None:
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite database not found: {sqlite_path}")

    validate_postgres_url(postgres_url)

    sqlite_conn = sqlite3.connect(sqlite_path)
    sqlite_conn.row_factory = None

    with psycopg2.connect(postgres_url) as pg_conn:
        with pg_conn.cursor() as pg_cursor:
            if reset:
                pg_cursor.execute(DROP_SQL)

            pg_cursor.execute(SCHEMA_SQL)

            if reset:
                for table in reversed(TABLE_ORDER):
                    pg_cursor.execute(f'TRUNCATE TABLE "{table}" RESTART IDENTITY CASCADE')

            for table in TABLE_ORDER:
                columns, rows = sqlite_rows(sqlite_conn, table)
                insert_table(pg_cursor, table, columns, rows)
                print(f"{table}: {len(rows)} rows")

            for table, id_column in IDENTITY_COLUMNS.items():
                reset_identity_sequence(pg_cursor, table, id_column)

        pg_conn.commit()

    sqlite_conn.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Migrate the cleaned FRAS SQLite database to PostgreSQL.")
    parser.add_argument("--sqlite", type=Path, default=DEFAULT_SQLITE_PATH, help="Path to attendance.db")
    parser.add_argument("--postgres", default=None, help="PostgreSQL DATABASE_URL; defaults to env DATABASE_URL")
    parser.add_argument("--reset", action="store_true", help="Drop/recreate FRAS tables before importing")
    args = parser.parse_args()

    postgres_url = args.postgres or postgres_url_from_env()
    migrate(args.sqlite, postgres_url, args.reset)
    print("Migration complete.")


if __name__ == "__main__":
    main()
